#if !canImport(ObjectiveC)
import XCTest

extension AETests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AETests = [
        ("testCoreShortcut", testCoreShortcut),
        ("testMy", testMy),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AETests.__allTests__AETests),
    ]
}
#endif
